# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b045c3fb6620391b2b8d20a417cecb2c53cca2ef2725a88a042592ee2b6ec9f4103c8b08e1a3d94cd87bbc2e704be7a2973c738f03e872365b54952920851bc

test:
  secret_key_base: 4edf1532b83783d0e2cc075bca04ed937236ac6e99101d2a5ea654359e13a138def9017f45e25ec651b205aeb5f1de929d55e1d51b7e837390071ea203cd029a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
